current_version: "1.12.3"
base_branch: "master"
strategy:
  name: "semver"
  part: "minor"
tag:
  apply: True
  format: "v{version}"
commit:
  author: ervitis
auto_remote_push: True
tracked_files:
  - Dockerfile
  - .github/workflows/docker_push.yml
  - README.md