name: push-image

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
     - name: Set up qemu
       uses: docker/setup-qemu-action@v2

     - name: Set up docker buildx
       uses: docker/setup-buildx-action@v2

     - name: Login
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Build and push
       uses: docker/build-push-action@v3
       with:
          push: true
          tags: ervitis/oapi-codegen:v1.12.2